// Generated by Haxe 4.1.1
#include <hxcpp.h>

namespace hx {
const char *__hxcpp_all_files[] = {
#ifdef HXCPP_DEBUGGER
"/opt/haxe/std/EnumValue.hx",
"/opt/haxe/std/IntIterator.hx",
"/opt/haxe/std/cpp/_std/Reflect.hx",
"/opt/haxe/std/cpp/_std/Std.hx",
"/opt/haxe/std/cpp/_std/StringBuf.hx",
"/opt/haxe/std/cpp/_std/Type.hx",
"/opt/haxe/std/cpp/_std/haxe/Exception.hx",
"/opt/haxe/std/cpp/_std/haxe/NativeStackTrace.hx",
"/opt/haxe/std/haxe/CallStack.hx",
"/opt/haxe/std/haxe/ValueException.hx",
"/opt/haxe/std/haxe/ds/Vector.hx",
"/opt/haxe/std/haxe/iterators/ArrayIterator.hx",
"/opt/haxe/std/haxe/iterators/ArrayKeyValueIterator.hx",
"reservedseating/ReservedSeating.hx",
#endif
 0 };

const char *__hxcpp_all_files_fullpath[] = {
#ifdef HXCPP_DEBUGGER
"/opt/haxe/std/EnumValue.hx",
"/opt/haxe/std/IntIterator.hx",
"/opt/haxe/std/cpp/_std/Reflect.hx",
"/opt/haxe/std/cpp/_std/Std.hx",
"/opt/haxe/std/cpp/_std/StringBuf.hx",
"/opt/haxe/std/cpp/_std/Type.hx",
"/opt/haxe/std/cpp/_std/haxe/Exception.hx",
"/opt/haxe/std/cpp/_std/haxe/NativeStackTrace.hx",
"/opt/haxe/std/haxe/CallStack.hx",
"/opt/haxe/std/haxe/ValueException.hx",
"/opt/haxe/std/haxe/ds/Vector.hx",
"/opt/haxe/std/haxe/iterators/ArrayIterator.hx",
"/opt/haxe/std/haxe/iterators/ArrayKeyValueIterator.hx",
"/my-component/src/reservedseating/ReservedSeating.hx",
#endif
 0 };

const char *__hxcpp_all_classes[] = {
#ifdef HXCPP_DEBUGGER
"_EnumValue.EnumValue_Impl_",
"IntIterator",
"Reflect",
"Std",
"StringBuf",
"Type",
"haxe._CallStack.CallStack_Impl_",
"haxe.Exception",
"haxe.NativeStackTrace",
"haxe.ValueException",
"haxe.ds._Vector.Vector_Impl_",
"haxe.iterators.ArrayIterator",
"haxe.iterators.ArrayKeyValueIterator",
"reservedseating.ReservedSeating",
#endif
 0 };
} // namespace hx
void __files__boot() { __hxcpp_set_debugger_info(::hx::__hxcpp_all_classes, ::hx::__hxcpp_all_files_fullpath); }
